version: '3'

services:
    sms-db:
        image: mysql:5.7
        container_name: start
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_HOST: '%'